# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsOfPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('station', models.CharField(max_length=64, null=True, verbose_name='站点')),
                ('qty', models.IntegerField(null=True, verbose_name='订单数量')),
                ('count', models.IntegerField(null=True, verbose_name='总数')),
                ('currencycode', models.CharField(max_length=32, null=True, verbose_name='币种')),
                ('site_price', models.CharField(max_length=128, null=True, verbose_name='站点金额')),
                ('dollar_price', models.CharField(max_length=128, null=True, verbose_name='美元金额')),
                ('RMB_price', models.CharField(max_length=128, null=True, verbose_name='人民币金额')),
                ('sametermrate', models.CharField(max_length=64, null=True, verbose_name='同比')),
                ('weekrate', models.CharField(max_length=64, null=True, verbose_name='周环比')),
                ('monthrate', models.CharField(max_length=64, null=True, verbose_name='月环比')),
            ],
            options={
                'verbose_name': '站点每日统计',
                'verbose_name_plural': '站点每日统计',
            },
        ),
    ]
