# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asininfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='reportdata',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='statisticsdata',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='statisticsofplatform',
            name='create_time',
        ),
    ]
