# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_statisticsofplatform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticsdata',
            options={'verbose_name': '单品每日统计', 'verbose_name_plural': '单品每日统计'},
        ),
        migrations.AlterModelOptions(
            name='statisticsofplatform',
            options={'verbose_name': '站点每日总计', 'verbose_name_plural': '站点每日总计'},
        ),
        migrations.AddField(
            model_name='statisticsofplatform',
            name='platform',
            field=models.CharField(max_length=32, null=True, verbose_name='账号'),
        ),
    ]
