# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_amazonproductbaseinfo_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='Reserved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
