# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20170926_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='Reserved',
            new_name='reserved',
        ),
    ]
