# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonRefShopList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_url', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(blank=True, max_length=8, null=True)),
                ('brand', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'amazon_ref_shop_list',
            },
        ),
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shop_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_30_days', models.IntegerField(blank=True, null=True)),
                ('last_90_days', models.IntegerField(blank=True, null=True)),
                ('last_12_months', models.IntegerField(blank=True, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
                ('last_day', models.IntegerField(blank=True, null=True)),
                ('last_week', models.IntegerField(blank=True, null=True)),
                ('last_month', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('zone', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'feedback',
            },
        ),
    ]
