# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255, verbose_name='商品编号')),
                ('zone', models.CharField(max_length=64, verbose_name='区域')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
                ('start_time', models.DateTimeField(verbose_name='执行开始时间')),
                ('end_time', models.DateTimeField(verbose_name='执行结束时间')),
                ('days', models.IntegerField(verbose_name='天数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '订单查询',
                'verbose_name_plural': '订单查询',
            },
        ),
    ]
