# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_ordercrawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercrawl',
            name='profile',
            field=models.CharField(default='ee', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='asin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='days',
            field=models.IntegerField(verbose_name='步长天数'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='zone',
            field=models.CharField(max_length=64, verbose_name='站点'),
        ),
    ]
