# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20170809_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercrawl',
            name='zone',
            field=models.CharField(choices=[('DE', 'DE'), ('CA', 'CA'), ('US', 'US'), ('JP', 'JP')], default='US', max_length=16, verbose_name='站点'),
        ),
    ]
