# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_ordercrawl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercrawl',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 9, 15, 53, 41, 202261), editable=False, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 9, 15, 53, 41, 202338), editable=False, verbose_name='执行结束时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 9, 15, 53, 41, 202305), editable=False, verbose_name='执行开始时间'),
        ),
    ]
