# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_auto_20170809_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercrawl',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 9, 16, 27, 55, 437575), editable=False, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 9, 16, 27, 55, 437653), editable=False, verbose_name='执行结束时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 9, 16, 27, 55, 437620), editable=False, verbose_name='执行开始时间'),
        ),
    ]
