# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20170809_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercrawl',
            name='add_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='执行结束时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='start_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='执行开始时间'),
        ),
    ]
