# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_auto_20170809_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercrawl',
            name='add_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='步长天数'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='执行结束时间'),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='name',
            field=models.CharField(blank=True, help_text='购买人姓名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordercrawl',
            name='start_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='执行开始时间'),
        ),
    ]
