# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0010_auto_20170809_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=64, verbose_name='日期')),
                ('count', models.IntegerField(verbose_name='抓取订单数量')),
                ('success', models.IntegerField(verbose_name='成功获取profile数量')),
            ],
        ),
    ]
