# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0011_countofday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countofday',
            old_name='day',
            new_name='order_day',
        ),
        migrations.RenameField(
            model_name='countofday',
            old_name='count',
            new_name='total',
        ),
    ]
