# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0012_auto_20170822_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countofday',
            name='success',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='成功获取profile数量'),
        ),
        migrations.AlterField(
            model_name='countofday',
            name='total',
            field=models.IntegerField(default=0, verbose_name='抓取订单数量'),
        ),
    ]
