# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0013_auto_20170822_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
