# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('zone', models.CharField(choices=[('DE', 'DE'), ('CA', 'CA'), ('US', 'US'), ('JP', 'JP')], default='US', max_length=16, verbose_name='站点')),
                ('order_id', models.CharField(max_length=255)),
                ('order_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='下单时间')),
            ],
            options={
                'verbose_name': '订单查询',
                'db_table': 'amazon_order_search_data',
                'verbose_name_plural': '订单查询',
            },
        ),
    ]
