# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='order_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='下单时间'),
        ),
    ]
