# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='create_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='插入时间'),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='update_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='插入时间'),
        ),
    ]
