# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170817_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='order_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='profile',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
