# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_auto_20170818_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(editable=False, null=True, verbose_name='添加时间')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '意见/建议',
                'verbose_name_plural': '意见/建议',
            },
        ),
    ]
