# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_advise'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('zone', models.CharField(choices=[('DE', 'DE'), ('CA', 'CA'), ('US', 'US'), ('JP', 'JP')], default='US', max_length=16, verbose_name='站点')),
                ('order_id', models.CharField(db_index=True, max_length=255)),
                ('order_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='下单时间')),
                ('create_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新时间')),
                ('status', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单查询',
                'verbose_name_plural': '订单查询',
            },
        ),
    ]
