# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_amazonorderitemlocal_amazonorderitemremote_amazonorderlocal_amazonorderremote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amazonorderitemlocal',
            table='amazon_order_item_local',
        ),
    ]
